# Generated by Django 5.2.3 on 2025-07-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Manichiura clasica', 'Manichiură clasică'), ('Semipermanenta', 'Manichiură semipermanentă'), ('Gel', 'Construcție cu gel'), ('Cosmetica', 'Tratamente cosmetice')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
