# Generated by Django 5.2.3 on 2025-07-03 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('manicure_classic', 'Manichiură clasică'), ('manicure_semi', 'Manichiură semipermanentă'), ('gel_build', 'Construcție gel'), ('gel_slim', 'Construcție slim'), ('gel_maintenance', 'Întreținere gel'), ('pedicure_classic', 'Pedichiură clasică'), ('pedicure_semi', 'Pedichiură ojă semipermanentă'), ('epilat_long', 'Epilat lung'), ('epilat_short', 'Epilat scurt'), ('epilat_inghinal', 'Epilat inghinal total'), ('epilat_axila', 'Epilat axilă'), ('epilat_brate', 'Epilat brațe'), ('epilat_mustata', 'Epilat mustață'), ('epilat_spate_abdomen', 'Epilat spate & abdomen'), ('pensat', 'Pensat'), ('vopsit_sprancene_gene', 'Vopsit sprâncene/gene')], max_length=50),
        ),
    ]
