# Generated by Django 5.2.3 on 2025-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_appointment_email_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('confirmed', 'Confirmată'), ('canceled', 'Anulată'), ('completed', 'Finalizată'), ('no_show', 'Nu s-a prezentat')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking.appointment')),
            ],
        ),
    ]
